#!/usr/bin/env python
"""Create a report of when students submitted a test."""
import pandas as pd
import os


def read_data(filename):
    """Read in CSV files from the data folder."""
    return pd.read_csv(os.path.join(
        os.path.dirname(__file__), "..", "data", filename
        ))


class_list = read_data("students.csv")
submissions = read_data("submissions.csv")
git_names = read_data("gitnames.csv")

# Create a mapping from Imperial usernames to GitHub names.
name_map = {imperial: git
            for imperial, git in zip(git_names["ImperialID"], git_names["GitHubID"])}

# Map GitHub names to submission times.
submissions_map = {
    git: time for git, time in zip(submissions["User"], submissions["SubmissionTime"])
}

class_list["Username"] = class_list["Username"].str.lower().map(name_map)
# For each student in the class, find their submission time.
submission_times = class_list["Username"].map(submissions_map)
submission_times = pd.Series(submission_times, name="SubmissionTimes")

dict_report = {
    "FirstName": class_list["FirstName"],
    "Surname": class_list["Surname"],
    "Username": class_list["Username"],
    "SubmissionTimes": submission_times
}

report = pd.DataFrame(dict_report)

report.to_csv("report.csv", index=False)

print("Report complete.")
